# R 프로그래밍

> "작성 중"

- toc: true
- branch: master
- badges: true
- comments: true
- author: 한재수
- categories: [R]

참고: R 프로그래밍 - 허명회 지음

`-` R 프로그래밍에 대해 복습할 겸 간단히 정리

# 2장 - 벡터(vector)
`-` 데이터 컨테이너의 기본형

## 벡터

In [2]:
#hide
import os
os.environ['R_HOME']='C:/anaconda3/envs/py38r40/lib/R' 

In [3]:
import rpy2
%load_ext rpy2.ipython

C:\anaconda3\envs\py38r40\lib\site-packages\rpy2\robjects\packages.py:366: UserWarning: The symbol 'quartz' is not in this R namespace/package.
  warnings.warn(


In [2]:
%%R
x <- 1
is.vector(x)

[1] TRUE


`-` x는 `길이가 1인 벡터 = 스칼라`

In [6]:
%%R 
print(pi)
print(pi, 16)

[1] 3.141593
[1] 3.141592653589793


`-` π는 숫자가 예약되어 있는 스칼라

In [10]:
%%R
M <- matrix(1:12, nrow = 4, ncol = 3, byrow = T)
M

     [,1] [,2] [,3]
[1,]    1    2    3
[2,]    4    5    6
[3,]    7    8    9
[4,]   10   11   12


`-` M은 행렬 ---> 벡터의 2차원 배열

## 인덱싱 

In [18]:
%%R
f <- c(1, 1, 2, 3, 5, 8, 13, 21)
f[5]

[1] 5


In [20]:
%%R
f[1:5]

[1] 1 1 2 3 5


In [21]:
%%R
f[-c(1,4)]

[1]  1  2  5  8 13 21


In [22]:
%%R
f[c(1,2,4)]

[1] 1 1 3


## seq()와 rep() 함수
`-` seq(a, b, by = c)는 a부터 b까지 c간격으로 등차수열 생성

In [23]:
%%R
seq(0, 10, 2.5)

[1]  0.0  2.5  5.0  7.5 10.0


`-`  seq(a, b, length = n)는 a부터 b까지 길이가 n인 일정 간격 수열을 생성

In [25]:
%%R
seq(0, 10, length = 11)

 [1]  0  1  2  3  4  5  6  7  8  9 10


`-` rep(x, times = k)는 x의 각 요소가 k의 각 요소씩 반복된 벡터

In [27]:
%%R
rep(NA, 5)

[1] NA NA NA NA NA


In [29]:
%%R
rep(c(1, 2), 3)

[1] 1 2 1 2 1 2


In [30]:
%%R
rep(c(1, 2, 3), c(3, 2, 1))

[1] 1 1 1 2 2 3


`-` rep(x, each = k)는 x의 각 요소가 각각 k번 반복된 벡터

In [32]:
%%R
rep(c(1, 2), each = 3)

[1] 1 1 1 2 2 2


## 필터링 
`-` 조건에 부합하는 데이터 값만 추출

In [33]:
%%R
x <- 1:10
x[x %% 2 == 1]

[1] 1 3 5 7 9


In [35]:
%%R
subset(x, x %% 2 == 0)

[1]  2  4  6  8 10


## ifelse() 함수 
`-` ifelse(x, yes, no)는 x가 True이면 yes를 값으로 하고 False이면 no를 값으로 배출

In [36]:
%%R
x <- 1:10
x1 <- ifelse(x %% 2 == 0, x, 2*x)
cbind(x, x1)

       x x1
 [1,]  1  2
 [2,]  2  2
 [3,]  3  6
 [4,]  4  4
 [5,]  5 10
 [6,]  6  6
 [7,]  7 14
 [8,]  8  8
 [9,]  9 18
[10,] 10 10


## names() 함수 
`-` names(x)는 벡터x의 개별 요소에 이름을 부여함

In [71]:
%%R
era <- c(5, 4 ,3, 4 ,5, 6)
era

[1] 5 4 3 4 5 6


`-` paste()함수는 2개의 문자열 벡터를 sep인수로 붙인다

In [72]:
%%R
names(era) <- paste("y", 2001:2006, sep = "-")
era

y-2001 y-2002 y-2003 y-2004 y-2005 y-2006 
     5      4      3      4      5      6 


# 3장 - 행렬(matrix) 
`-` $p$개의 길이 $n$인 벡터를 열에 배치함

## 행렬 

In [37]:
%%R
n <- 100
p <- 3
x <- rnorm(n*p)
A <- matrix(x, nrow = n, ncol = p)
A[1:6, ]

           [,1]        [,2]       [,3]
[1,] -0.5272115 -0.09766999  0.9157430
[2,] -0.4910666  0.27630674 -0.4863826
[3,] -0.7199871 -1.37864849 -0.1378880
[4,] -0.2978141  1.21144373 -1.1352895
[5,] -0.9412001 -1.05635910  1.0677189
[6,] -0.4909131  0.92592424 -1.8697058


`-` 콤마(,)앞은 행, 콤마(,)뒤는 열

In [38]:
%%R
A[1:6, 1:2]

           [,1]        [,2]
[1,] -0.5272115 -0.09766999
[2,] -0.4910666  0.27630674
[3,] -0.7199871 -1.37864849
[4,] -0.2978141  1.21144373
[5,] -0.9412001 -1.05635910
[6,] -0.4909131  0.92592424


`-` 필터링을 통해 인덱싱도 가능

In [42]:
%%R
A[A[,3] > 0 & A[,2] > 0, ]

              [,1]       [,2]       [,3]
 [1,] -1.632001082 0.95386709 0.34696994
 [2,] -0.388047387 0.75046872 0.61005479
 [3,] -1.325637032 0.85805657 0.48388600
 [4,]  1.027718630 1.93877622 0.04144039
 [5,] -0.926911907 0.57212123 1.66361085
 [6,]  2.120355231 0.25362934 0.64836355
 [7,]  1.038120371 0.01903657 0.04071902
 [8,] -0.973632914 0.35330337 0.35594054
 [9,]  1.799568590 1.98855528 0.50952846
[10,]  0.633299053 1.03079130 0.23844919
[11,] -0.178793903 0.66631102 1.11482316
[12,]  1.307643075 0.14501150 0.41404295
[13,]  0.005313813 2.02583488 0.33820766
[14,] -0.280283865 1.04242405 1.33195196
[15,]  0.270559357 0.05230981 0.35938639
[16,] -1.485066480 0.41976340 0.59734787
[17,] -0.076204339 0.97655368 1.99341983
[18,]  2.316420281 0.05287762 0.27840240
[19,] -0.661999001 0.28495938 1.43514281
[20,] -0.713879760 0.15816804 0.71605743
[21,] -0.095003851 1.13276296 0.74928887
[22,]  0.087418924 1.66296778 0.47576952
[23,] -1.055728878 0.56180370 1.26128539
[24,]  1.1532900

`-` t(A) 함수는 행렬 A의 전치행렬을 구해줌

In [43]:
%%R
B <- matrix(1:9, 3, 3)
B

     [,1] [,2] [,3]
[1,]    1    4    7
[2,]    2    5    8
[3,]    3    6    9


In [44]:
%%R
t(B)

     [,1] [,2] [,3]
[1,]    1    2    3
[2,]    4    5    6
[3,]    7    8    9


`-` solve()함수는 역행렬을 구해줌

In [49]:
%%R
C <- matrix(c(16 ,4, 1, 4, 4, 1, 1, 1, 1), 3, 3)
C

     [,1] [,2] [,3]
[1,]   16    4    1
[2,]    4    4    1
[3,]    1    1    1


In [50]:
%%R
solve(C)

            [,1]        [,2]       [,3]
[1,]  0.08333333 -0.08333333  0.0000000
[2,] -0.08333333  0.41666667 -0.3333333
[3,]  0.00000000 -0.33333333  1.3333333


`-` %*%는 행렬곱

In [48]:
%%R
solve(C) %*% C

             [,1]          [,2]          [,3]
[1,] 1.000000e+00 -5.551115e-17 -1.387779e-17
[2,] 1.665335e-16  1.000000e+00  5.551115e-17
[3,] 0.000000e+00  0.000000e+00  1.000000e+00


`-` 참고로 $AA^{-1} = I$

`-` $I$는 [단위행렬](https://ko.wikipedia.org/wiki/%EB%8B%A8%EC%9C%84%ED%96%89%EB%A0%AC)

## apply() 함수 

`-` apply(A, 1 or 2, f) ---> 행렬A의 행(1) or 열(2)에 함수 f를 적용 

`-` c(1, 2)는 행과 열에 적용 ---> 각 원소

In [104]:
%%R
M <- matrix(1:12, 3, 4)
M

     [,1] [,2] [,3] [,4]
[1,]    1    4    7   10
[2,]    2    5    8   11
[3,]    3    6    9   12


`-` apply에서 옵션을 1(행)로 하니 전치된 행렬을 반환함

In [113]:
%%R
max_ = apply(M, 2, max)
apply(M, 1, "-", max_)

     [,1] [,2] [,3]
[1,]   -2   -1    0
[2,]   -2   -1    0
[3,]   -2   -1    0
[4,]   -2   -1    0


In [114]:
%%R
max_ = apply(M, 2, max)
t(apply(M, 1, "-", max_))

     [,1] [,2] [,3] [,4]
[1,]   -2   -2   -2   -2
[2,]   -1   -1   -1   -1
[3,]    0    0    0    0


`-` apply에서 옵션을 2(열)로 하니 문제 없어보임

In [111]:
%%R
max_ = apply(M, 1, max)
apply(M, 2, "-", max_)

     [,1] [,2] [,3] [,4]
[1,]   -9   -6   -3    0
[2,]   -9   -6   -3    0
[3,]   -9   -6   -3    0


`-` 옵션을 c(1, 2)로 하니 각 원소에서 -1을 수행함

In [96]:
%%R
apply(M, 1:2, "-", 1)

     [,1] [,2] [,3] [,4]
[1,]    0    3    6    9
[2,]    1    4    7   10
[3,]    2    5    8   11


`-` 행렬의 각 열에 대해 최소값 0과 최대값 1이 되도록 변환

In [128]:
%%R
n <- 5
p <- 4
M <- matrix(rnorm(n*p), n, p)
M

            [,1]        [,2]       [,3]        [,4]
[1,]  0.39140070  0.41656975  0.3387848  0.15505716
[2,]  1.82931560 -1.25805693 -1.3580300  0.08618929
[3,] -0.07224563 -0.01837199  1.1249997  0.16007225
[4,]  1.05756759 -0.33926353  0.8730712 -0.51535640
[5,]  1.35992572  0.06295887  0.2480695 -2.54631691


In [139]:
%%R
min_ <- apply(M, 2, min)
max_ <- apply(M, 2, max)
M.1 <- t(apply(M, 1, "-", min_))
M.2 <- t(apply(M.1, 1, "/", max_-min_))
M.2

          [,1]      [,2]      [,3]      [,4]
[1,] 0.2438240 1.0000000 0.6833647 0.9981469
[2,] 1.0000000 0.0000000 0.0000000 0.9727005
[3,] 0.0000000 0.7402754 1.0000000 1.0000000
[4,] 0.5941503 0.5486557 0.8985399 0.7504318
[5,] 0.7531555 0.7888420 0.6468306 0.0000000


## rownames()와 colnames() 함수
`-` 행렬의 행과 열에 이름을 붙임

In [141]:
%%R
n <- 10
x <- matrix(round(rnorm(n*4, 50, 10)), n, 4) ## 평균이 50, 표준편차가 10인 정규분포에서 난수 40개 추출
rownames(x) <- paste("S", 1:n, sep = "")
colnames(x) <- c("math", "engl", "science", "arts")
x

    math engl science arts
S1    48   63      48   42
S2    40   46      45   60
S3    48   47      65   54
S4    29   53      56   35
S5    42   63      42   46
S6    30   67      57   55
S7    59   44      41   47
S8    44   48      40   60
S9    45   67      43   58
S10   66   54      72   73


# 4장 - 리스트(list) 
`-` R에서 가장 일반적인 데이터 형태

In [27]:
%%R
members <- list(leaders = c("gang", "iu"), assisstants = "kang")
members

$leaders
[1] "gang" "iu"  

$assisstants
[1] "kang"



`-` class(X) 함수는 X의 type을 알려줌

In [28]:
%%R
class(members)

[1] "list"


`-` names()함수로 요소의 라벨을 확인 + 변경 가능

In [29]:
%%R
print(names(members))
names(members)[2] <- "workers"
print(names(members))

[1] "leaders"     "assisstants"
[1] "leaders" "workers"


## 리스트에 접근하기 

`-` `[[  ]]` 사용

In [30]:
%%R
members[[1]]

[1] "gang" "iu"  


`-` `[ ]`은 sublist

`-` `[[  ]]`은 벡터이고 `[ ]`은 리스트임

In [31]:
%%R
members[1]

$leaders
[1] "gang" "iu"  



`-` 요소 이름 사용

In [33]:
%%R
members[["leaders"]]

[1] "gang" "iu"  


`-` `$` 기호 사용 ---> 개인적으로 제일 편함

In [35]:
%%R
members$leaders

[1] "gang" "iu"  


`-` 리스트 내 자료 값 변경도 가능

In [36]:
%%R
members$leaders[1] <- "park"
members

$leaders
[1] "park" "iu"  

$workers
[1] "kang"



## lapply()와 sapply() 함수 
`-` matrix에서 apply() 함수를 사용하듯이 리스트에선 `lapply()`와 `sapply()` 함수를 사용

`-` `lapply(list, fun)`는 list 내 요소들에 함수 fun을 적용하여 결과를 `리스트`로 출력 ---> `sapply()` 는 `벡터`로 출력

In [37]:
%%R
salaries <- list(leaders = c(250, 200), assistant = 100, members = c(300, 200, 180, 120 ,100))
salaries

$leaders
[1] 250 200

$assistant
[1] 100

$members
[1] 300 200 180 120 100



`-` lapply() 사용

In [38]:
%%R
lapply(salaries, mean)

$leaders
[1] 225

$assistant
[1] 100

$members
[1] 180



`-` sapply() 사용

`-` 벡터로 출력이 불가능할 때는 lapply() 처럼 list로 출력함

In [39]:
%%R
sapply(salaries, mean)

  leaders assistant   members 
      225       100       180 


# 5장 - 데이터 프레임(data frame) 
`-` matrix는 요소가 숫자만 가능했다면 data frame은 문자열과 같은 다른 type도 가능함

`-` 데이터 프레임은 리스트의 일종

`-` 리스트는 각 변수마다 길이가 달라도 되지만 데이터 프레임은 각 변수마다 길이가 같아야 함(열의 길이가 동일)

In [26]:
%%R
course.id <- c(1, 2, 3, 4 ,5, 6 ,7, 8, 9 ,10)
mid <- c(8, 22, 25, 25 ,21, 12, 12, 29, 40, 25)
final <- c(11, 24, 31, 13 ,34 ,26, NA ,36, 34 ,38)
exams <- data.frame(course.id, mid, final)
exams

   course.id mid final
1          1   8    11
2          2  22    24
3          3  25    31
4          4  25    13
5          5  21    34
6          6  12    26
7          7  12    NA
8          8  29    36
9          9  40    34
10        10  25    38


In [5]:
%%R
is.list(exams)

[1] TRUE


In [7]:
%%R
colnames(exams)

[1] "course.id" "mid"       "final"    


In [8]:
%%R
names(exams)

[1] "course.id" "mid"       "final"    


In [9]:
%%R
length(exams)

[1] 3


`-` `[row, column]`으로 인덱싱

In [11]:
%%R
exams[exams$mid > 20, ]

   course.id mid final
2          2  22    24
3          3  25    31
4          4  25    13
5          5  21    34
8          8  29    36
9          9  40    34
10        10  25    38


In [19]:
%%R
exams[exams$mid > 20, 'final'] ## exams[exams$mid > 20, 3] 과 동일함

[1] 24 31 13 34 36 34 38


`-` 데이터 프레임의 각 열은 수치 벡터이므로 연산 가능

In [21]:
%%R
mean(exams[, "mid"])

[1] 21.9


In [22]:
%%R
mean(exams$final)

[1] NA


`-` 값이 NA로 나옴 ---> 7번 학생이 기말시험을 결시함

`-` 그럼 어떻게 평균을 구하지? ---> `na.rm = T` 옵션을 통해 NA를 제외한 데이터만 사용할 수 있음

In [23]:
%%R
mean(exams$final, na.rm = T)

[1] 27.44444


`-` 만약 시험을 결시한 경우 0점 처리 한다면? ---> `is.na()` 함수를 통해 NA인 경우 True를 아닌 경우 False를 생성하여 처리 가능

In [27]:
%%R
is.na(exams$final)

 [1] FALSE FALSE FALSE FALSE FALSE FALSE  TRUE FALSE FALSE FALSE


In [28]:
%%R
exams$final[is.na(exams$final)] <- 0  ## is.na가 True인 경우만 0으로 변경
exams

   course.id mid final
1          1   8    11
2          2  22    24
3          3  25    31
4          4  25    13
5          5  21    34
6          6  12    26
7          7  12     0
8          8  29    36
9          9  40    34
10        10  25    38


In [29]:
%%R
mean(exams$final)

[1] 24.7


## 두 데이터 프레임의 병합 

`-` exams 변수는 중간 기말 성적이 기록되어 있음

`-` 새로운 변수 book은 과제와 프로젝트 점수가 student_name의 순서로 정렬되어 있음

`-` 이 둘을 합쳐보자

In [30]:
%%R
student_name <- c('a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j')
homework <- c(22, 34, 31, 24, 37, 36, 37, 28, 37, 34)
project <- c(NA, 7, NA, NA, 17 ,10, 8, NA ,4, NA)
course.id <- c(8, 10, 5, 1, 4, 2, 3 ,9 ,7 ,6)
book <- data.frame(student_name, homework, project, course.id)
book

   student_name homework project course.id
1             a       22      NA         8
2             b       34       7        10
3             c       31      NA         5
4             d       24      NA         1
5             e       37      17         4
6             f       36      10         2
7             g       37       8         3
8             h       28      NA         9
9             i       37       4         7
10            j       34      NA         6


`-` NA는 자료의 수치 연산을 불가능하게 하므로 앞서 했던것처럼 is.na()를 통해 0점 처리하자

In [31]:
%%R
book$project[is.na(book$project)] <- 0
book

   student_name homework project course.id
1             a       22       0         8
2             b       34       7        10
3             c       31       0         5
4             d       24       0         1
5             e       37      17         4
6             f       36      10         2
7             g       37       8         3
8             h       28       0         9
9             i       37       4         7
10            j       34       0         6


`-` 2개의 데이터 프레임을 통합하고자 할 때 확인할 것은 각 데이터 프레임에서 개체들의 정렬순서

`1.` 2개의 프레임에서 순서가 같은 경우 열 묶음(cbind)를 한다 ---> cbind(exams, book)

`-` 하지만 course.id의 순서가 다르므로 불가능

`2.` 2개의 프레임에서 그 순서가 다른 경우 `공통 개체 식별자(key)`를 찾아 정의 ---> `merge()` 함수가 key 변수를 찾아줌  

In [35]:
%%R
class_record <- merge(exams, book, by = 'course.id')
class_record

   course.id mid final student_name homework project
1          1   8    11            d       24       0
2          2  22    24            f       36      10
3          3  25    31            g       37       8
4          4  25    13            e       37      17
5          5  21    34            c       31       0
6          6  12    26            j       34       0
7          7  12     0            i       37       4
8          8  29    36            a       22       0
9          9  40    34            h       28       0
10        10  25    38            b       34       7


`-` 위와 같이 key 변수의 이름(위에서는 course.id)이 두 데이터 프레임에서 동일한 경우 `by`를 사용 ---> 그렇지 않은 경우에는 `by.x`와 `by.y`를 사용

`-` 학생들의 총 점수 합계를 구하여 데이터 프레임에 새 변수로 추가해보자

In [40]:
%%R
class_record$total <- apply(class_record[ ,c(2, 3, 5, 6)], 1, sum)
class_record

   course.id mid final student_name homework project total
1          1   8    11            d       24       0    43
2          2  22    24            f       36      10    92
3          3  25    31            g       37       8   101
4          4  25    13            e       37      17    92
5          5  21    34            c       31       0    86
6          6  12    26            j       34       0    72
7          7  12     0            i       37       4    53
8          8  29    36            a       22       0    87
9          9  40    34            h       28       0   102
10        10  25    38            b       34       7   104
