# 희소 행렬

> "작성 중"

- toc: true
- branch: master
- badges: true
- comments: true
- author: 한재수
- categories: [Math]

`-` 행렬 정리글: https://jaesu26.github.io/green/math/2021/09/16/행렬.html

`-` ref: https://en.wikipedia.org/wiki/Sparse_matrix

# 희소 행렬

`-` `희소 행렬(sparse matrix)`: 값이 대부분 $0$인 행렬 

`-` `희소성(sparsity)`: 행렬의 전체 원소 중 $0$인 원소의 비율

`-` 희소(sparse)하다고 말할 수 있는 정확한 정의는 없지만 일반적인 기준은 $0$이 아닌 원소가 대략 행 또는 열의 수만큼 있는 것이다

## 희소 행렬의 자료구조

In [29]:
import numpy as np

arr = np.array([[1, 2, 0, 0, 0], [0, 0, 0, 0, 0], [0, 0, 0, 3, 0], [0, 0, 4, 0, 0], [5, 0, 0, 0, 6]])
print(arr)  # 25개의 원소 중 19개가 0인 희소 행렬

[[1 2 0 0 0]
 [0 0 0 0 0]
 [0 0 0 3 0]
 [0 0 4 0 0]
 [5 0 0 0 6]]


### Dictionary of keys (DOK)

`-` (row, column)을 value로 매핑한 딕셔너리 구조

In [20]:
from scipy.sparse import dok_matrix

S = dok_matrix((5, 5), dtype=np.float32)
for i in range(5):
    for j in range(5):
        S[i, j] = i + j    # Update element

In [38]:
print(S.todense())

[[0. 1. 2. 3. 4.]
 [1. 2. 3. 4. 5.]
 [2. 3. 4. 5. 6.]
 [3. 4. 5. 6. 7.]
 [4. 5. 6. 7. 8.]]


### List of lists (LIL)

`-` 각 행마다 열의 인덱스와 값을 하나의 리스트로 저장하는 구조

In [7]:
from scipy.sparse import lil_matrix

In [30]:
lil = lil_matrix(arr)

In [42]:
print(lil.rows)  # 행마다ㅏ 0이 아닌 값의 열 인덱스

[list([0, 1]) list([]) list([3]) list([2]) list([0, 4])]


In [41]:
print(lil.data)  # 행마다 0이 아닌 값을 저장

[list([1, 2]) list([]) list([3]) list([4]) list([5, 6])]


### Coordinate list (COO)

`-` (row, column, value) 튜플을 리스트에 저장한 구조

In [43]:
from scipy.sparse import coo_matrix

In [44]:
coo = coo_matrix(arr)

In [56]:
print(coo.row, coo.col, coo.data)

[0 0 2 3 4 4] [0 1 3 2 0 4] [1 2 3 4 5 6]


In [53]:
for row, col, value in zip(coo.row, coo.col, coo.data):
    print(f'{row}행 {col}열에 저장된 값: {value}')

0행 0열에 저장된 값: 1
0행 1열에 저장된 값: 2
2행 3열에 저장된 값: 3
3행 2열에 저장된 값: 4
4행 0열에 저장된 값: 5
4행 4열에 저장된 값: 6
